# -*- coding: utf-8 -*-
"""OOP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lck1wRQ7p0ImZxsQDZ_AoTjerSR4rwcF
"""

class telefono:
  def __init__(self, marca, color, modelo, memoria):
    self.marca = marca
    self.color = color
    self.modelo = modelo
    self.memoria = memoria
  def llamar(self):
    print(f"Llamando desde tu {self.marca} {self.modelo}")
  def colgar(self):
    print(f"Colgando desde tu {self.marca} {self.modelo}")
  def foto(self):
    print(f"Tomando foto con tus {self.modelo}")

telefono1 = telefono("samsung", "negro", "s26", "128gb")
telefono2 = telefono("iphone", "naranja", "17", "256gb")
telefono3 = telefono("xiaomi", "verde", "17", "528gb")
telefono4 = telefono("oneplus", "blanco", "nord5", "526gb")

#Comprobar atributos
print(f"Los telefonos disponibles son: 1.{telefono1.marca}, 2.{telefono2.marca}, 3.{telefono3.marca}, 4.{telefono4.marca}")
print("Introduzca el numero del telefono cuyas especificaciones quiera ver: ")
telefono_mostrar = input()
if telefono_mostrar == "1":
  telefono = telefono1
elif telefono_mostrar == "2":
  telefono = telefono2
elif telefono_mostrar == "3":
  telefono = telefono3
elif telefono_mostrar == "4":
    telefono = telefono4
print(f"El primer telefono es de la marca {telefono.marca}, color {telefono.color}, modelo {telefono.modelo}, y cuenta con {telefono.memoria} de memoria interna")

#Ejecutar métodos
print(f"Que desea hacer con su {telefono.marca}")
print("Si desea llamar introduzca 1, si desea colgar introduzca 2, si desea tomar una foto introduzca 3 :")
opcion = input()
if opcion == "1":
  telefono.llamar()
elif opcion == "2":
  telefono.colgar()
elif opcion == "3":
  telefono.foto()
print("Gracias por usar nuestros servicios")